### ISSUE TITLE
VARCHAR(10) is too small

### ISSUE THREAD

**Issue by williamdes** [umpirsky/tld-list#5]
@umpirsky the VARCHAR(10) is too small (IMO), the import of the sql file failed on some rows.

I think you need to set the id column to ~~VARCHAR(20)~~ VARCHAR(63) to be ok.

**Comment by williamdes** [comment]
Or acording to RFC ``` Labels must be 63 characters or less.``` https://tools.ietf.org/html/rfc1034#page-11

**Comment by umpirsky** [comment]
Woah, true. Thanks for reporting!
